### PR TITLE
fix(wan_s2v_dit): accept and propagate attn_kwargs (fixes #221)

### PR DESCRIPTION
**Pull request by daqiege**
## Summary
Fixes the regression reported in #221:

```
TypeError: WanS2VDiT.forward() got an unexpected keyword argument 'attn_kwargs'
```

## Root cause
Commit 4ae8f2c0 added `attn_kwargs` to `WanDiT` / `DiTBlock` and updated
`WanSpeech2VideoPipeline.predict_noise` to pass `attn_kwargs=...` when
calling the model — but `WanS2VDiT` (and its block class `DiTBlockS2V`)
were not updated, so every S2V inference call now raises `TypeError`.

## Fix
Mirror what was done for `WanDiT` / `DiTBlock`:

- `DiTBlockS2V.forward`: accept `attn_kwargs=None`, forward it to
  `self.self_attn(...)` and `self.cross_attn(...)` (these already
  accept `attn_kwargs`).
- `WanS2VDiT.forward`: accept `attn_kwargs: Optional[Dict[str, Any]] = None`,
  pass it through to each `block(...)` call.
- Add `Any, Dict` to the existing `typing` import.

When `attn_kwargs` is `None` the behavior is unchanged (matches
existing wan_dit attention paths, which treat `None` as "no extra
kwargs").

## Test plan
- [x] `python -m py_compile diffsynth_engine/models/wan/wan_s2v_dit.py` passes
- [x] No-op when `attn_kwargs=None` (default), so existing call sites that
      don't pass it stay backwards compatible
- [ ] Reviewer can confirm by re-running `examples/wan_speech_to_video.py`
      which previously raised the TypeError

Closes #221

### CODE REVIEW

**Comment by daqiege** [comment]
Thanks for the review! Updated to pass `attn_kwargs` as a keyword argument in both `self_attn(...)` and `cross_attn(...)` calls — agreed it's safer against future signature changes.
